from pathlib import Path

CURRENT_DIR = Path(__file__).parent
RESOURCES_DIR = CURRENT_DIR / "data"
PAUSE_BLINK_TIME_MS = 700
SIMON_SAYS_BLINK_TIME_MS = 400
TOAST_SHOW_TIME_MS = 1500
PLAYER_MOVE_SPEED = 200
PLAYER_RUN_SPEED = 400
