name: 🐛 Bug report
description: For reporting bugs. Please check for existing issues and read CONTRIBUTING
title: "[BUG] <title_here>"
labels: [Bug]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues and did not find any.
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to ...
      2. Click on ...
      3. Go to ...
  validations:
    required: false
- type: textarea
  attributes:
    label: Screenshots?
    description: |
      Do you have any screenshots that help explain the problem?

      Tip: You can attach images or (log) files by clicking this area to highlight it and then dragging files in.
- type: textarea
  attributes:
    label: Logfiles?
    description: |
      To help us diagnose your problem we ask you to provide the log file.
      This is located inside the root folder of the game and has the name `currentdate`.log

      Tip: You can attach images or (log) files by clicking this area to highlight it and then dragging files in.
- type: textarea
  attributes:
    label: Environment
    description: |
      Examples:
       - **OS**: Windows
       - **OS Version**: 10
       - **Python Version**: 3.7
       - **Game version**: Ran from sourcecode
    value: |
       - **OS**: 
       - **OS Version**: 
       - **Python Version**: 
       - **Game version**:
    render: markdown
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Code of Conduct
    description: The Code of Conduct helps to keep the community safe. We require everyone to agree to it.
    options:
      - label: I agree to follow this project's [Code of Conduct](CODE_OF_CONDUCT.md)
        required: true
- type: markdown
  attributes:
    value: "**We would like to thank you to filing a bug report!**"
