name: 'Build'
on:
  push:
    tags:
      - 'v*'
      - 'beta-v*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: changelog
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create Release For Tag
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ needs.changelog.outputs.changelog }}
        draft: false
        prerelease: ${{ contains(github.ref, 'beta') }}
  
  build:
    name: Build Executables
    needs: create_release
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.12'
      - name: Install dependencies for ${{ matrix.config.os }}
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build with pyinstaller for ${{ matrix.config.os }}
        run: pyinstaller swishandfrick.spec
      - name: Archive Release
        uses: thedoctor0/zip-release@0.6.2
        with:
          type: 'zip'
          path: './dist'
          filename: 'swishandfrick-${{runner.os}}.zip'
          exclusions: '*.git*'
      - name: Upload Artifact for ItchIO Uploader
        uses: actions/upload-artifact@v3
        with:
          name: ${{runner.os}}
          path: swishandfrick-${{runner.os}}.zip
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_content_type: application/zip
          asset_name: 'swishandfrick-${{runner.os}}.zip'
          asset_path: './swishandfrick-${{runner.os}}.zip'
  
  release_itchio:
    name: Release on itch.io
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel: [Linux, macOS, Windows]
    steps:
      - name: Downloading Artifacts for ${{ matrix.channel }}
        uses: actions/download-artifact@v3
        with:
          name: ${{matrix.channel}}
          path: './'
      - name: Display downloaded files
        run: ls -R
        working-directory: ./


      # - name: Upload ${{ matrix.preset }} to itch.io project
      #   uses: josephbmanley/butler-publish-itchio-action@master
      #   env:
      #     BUTLER_CREDENTIALS: ${{ secrets.ITCHIO_API_KEY }}
      #     CHANNEL: ${{ runner.os }}
      #     ITCH_GAME: swish-and-frick
      #     ITCH_USER: daanbreur
      #     PACKAGE: './swishandfrick-${{runner.os}}.zip'
      #     VERSION: ${{ github.ref_name }}