name: Welcome New Contributors
on:
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/welcome@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIRST_ISSUE: |
            👋 @{{ author }}
            Thanks for opening your first issue here! It's awesome you are helping us by reporting bugs and suggesting features.

          FIRST_PR: |
            👋 @{{ author }}
            Thanks for opening this pull request! Please check out our contributing guidelines.
            Helping with features and bugfixes is much appreciated.

          FIRST_PR_MERGED: |
            🎉 @{{ author }}
            Congrats on your first merged pull request! We are proud of you! 
            Thanks for helping us with this awesome bugfix or new feature.